// SPDX-FileCopyrightText: 2026 dSPACE SE & Co. KG
// SPDX-License-Identifier: Apache-2.0

/** <!-------------------------------------------------------------------------->
*
*   @file cycloneDdsProvider.cpp
*
*   @brief CycloneDDS backend implementation of the HSIL DDS abstraction layer.
*
*   @author
*       dSPACE SE & Co. KG
*
*   @description
*       Implements the HsilDdsOps vtable using the CycloneDDS C API (ddsc).
*       Creates DDS participants, writers, and readers for the GroupedData and
*       StreamingData types generated from the HSIL CoSim IDL by idlc. Each
*       reader uses a data-available listener to deliver samples asynchronously
*       to the callbacks registered in the HSIL session.
*
*   <hr><br>
*<!-------------------------------------------------------------------------->*/

/*----------------------------------------------------------------------------*/
/* INCLUDES                                                                   */
/*----------------------------------------------------------------------------*/

#include "cycloneDdsProvider.h"

/* CycloneDDS C API */
#include <dds/dds.h>
#include <dds/ddsrt/environ.h>

/* Type-support headers generated by idlc from HSIL-CoSim.idl.
 * idlc maps the IDL module HSIL_CoSim and generates:
 *   HSIL_CoSim_GroupedData    – struct with id, sequenceNumber, timestamp, data
 *   HSIL_CoSim_StreamingData  – struct with protocol[8], timestamp, meta, data
 * Sequence<octet> fields become dds_sequence_uint8_t (length / buffer / release). */
#include "HSIL-CoSim.h"

#include <cstdint>
#include <cstring>
#include <iostream>
#include <map>
#include <memory>
#include <string>

/*----------------------------------------------------------------------------*/
/* COMPILE-TIME ENDIANNESS CHECK                                               */
/* serializeMetaData / deserializeMetaData use direct memcpy of multi-byte    */
/* integers and therefore require a little-endian host.                       */
/*----------------------------------------------------------------------------*/

#if defined(__BYTE_ORDER__) && defined(__ORDER_LITTLE_ENDIAN__)
    /* GCC / Clang on Linux, macOS, MinGW on Windows */
    static_assert(__BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__,
                  "cycloneDdsProvider is currently not implemented for big-endian hosts.");
#elif defined(_MSC_VER)
    /* MSVC: all supported targets (x86, x64, ARM in LE mode) are little-endian.
     * Verify at least one of the known LE architecture macros is defined so we
     * catch any hypothetical big-endian MSVC target. */
    #if !defined(_M_IX86) && !defined(_M_X64) && !defined(_M_AMD64) && \
        !defined(_M_ARM)  && !defined(_M_ARM64)
        #error "Unrecognised MSVC target architecture – cannot verify endianness. " \
               "cycloneDdsProvider is currently implemented for only little-endian hosts."
    #endif
#else
    #error "Cannot determine host endianness for this compiler/platform. " \
           "cycloneDdsProvider is currently implemented for only little-endian hosts."
#endif

/*----------------------------------------------------------------------------*/
/* CONSTANTS                                                                   */
/*----------------------------------------------------------------------------*/

/** Maximum samples taken from a reader in one data-available callback invocation. */
static constexpr int HSIL_MAX_SAMPLES = 32;

/*----------------------------------------------------------------------------*/
/* VENDOR CONTEXT                                                              */
/*----------------------------------------------------------------------------*/

/**
 * @brief CycloneDDS-specific session state.
 *
 * Holds the DDS participant that is shared across all readers and writers
 * created for one HSIL session.
 */
struct CycloneCtx
{
    dds_entity_t participant; /**< DDS domain participant. */
};

/*----------------------------------------------------------------------------*/
/* READER / WRITER HANDLE TYPES                                               */
/*----------------------------------------------------------------------------*/

/**
 * @brief Context passed to the data-available listener of a GroupedData reader.
 */
struct CycloneGroupedReaderCtx
{
    HsilGroupedDataCallback callback;    /**< HSIL dispatch callback.         */
    void*                   callbackData; /**< Forwarded to every callback.  */
    char                    topicName[256]; /**< DDS topic name for the call. */
};

/**
 * @brief Context passed to the data-available listener of a StreamingData reader.
 */
struct CycloneStreamingReaderCtx
{
    HsilStreamingDataCallback callback;    /**< HSIL dispatch callback.       */
    void*                     callbackData; /**< Forwarded to every callback. */
    char                      topicName[256]; /**< DDS topic name.            */
};

/**
 * @brief Opaque reader handle returned to the abstraction layer.
 *
 * Bundles the DDS reader entity together with its listener context so both
 * can be freed when destroyReader() is called. The deleteCtx function pointer
 * performs a correctly typed delete of the listener context object.
 */
struct CycloneReaderHandle
{
    dds_entity_t    reader;      /**< DDS DataReader entity.                  */
    dds_listener_t* listener;    /**< Listener registered on the reader.      */
    void*           listenerCtx; /**< Heap-allocated listener context.        */
    void          (*deleteCtx)(void*); /**< Typed deleter for listenerCtx.    */
};

/*----------------------------------------------------------------------------*/
/* HELPER: META DATA SERIALIZE/ DE-SERIALIZE                                  */
/*----------------------------------------------------------------------------*/

struct SerializedMetaData
{
    static constexpr size_t HSIL_CAN_META_SIZE = 5; /**< CAN meta contians 2 bytes for message ID and 1 byte for frame type. */
    static constexpr size_t HSIL_CAN_MESSAGE_ID_SIZE = 4; /**< CAN message ID is serialized as 4 bytes. */
    static constexpr size_t HSIL_CAN_FRAME_TYPE_SIZE = 1; /**< CAN frame type is serialized as 1 byte. */
    
    static constexpr size_t HSIL_ETH_META_SIZE = 1; /**< Ethernet meta contains 1 byte Flag */
    static constexpr size_t HSIL_ETH_FLAGS_SIZE = 1; /**< Ethernet flags are serialized as 1 byte. */
    
    static constexpr size_t HSIL_ETHJ_META_SIZE = 5; /**< Jumbo Ethernet meta contains 4 bytes MTU and 1 byte Flag */
    static constexpr size_t HSIL_ETHJ_MTU_SIZE = 4; /**< Jumbo Ethernet MTU is serialized as 4 bytes. */
    static constexpr size_t HSIL_ETHJ_FLAGS_SIZE = 1; /**< Jumbo Ethernet flags are serialized as 1 byte. */


    size_t   size;
    uint8_t* serialBuffer;  /**< Pointer to the serialized meta data buffer. For "generic" points to the user supplied buffer or null. FOr all other protocols, points to the buffer of this struct */
    uint8_t  buffer[sizeof(HsilStreamingMetaData)];    /**< Large enough buffer to hold meta data from all the protocols except "generic" */
};

/**
 * @brief Serialize the meta data of a streaming sample into a byte buffer for transmission.
 *        The serialization format depends on the protocol:
 *        - For "CAN_v1": 4 bytes for the frame type (little-endian uint32) followed by 1 byte for the flags.
 *        - For "Eth_v1": 1 byte for the flags.
 *        - For "EthJ_v1": 4 bytes for the MTU (little-endian uint32) followed by 1 byte for the flags.
 *        - For "generic": the user-supplied buffer is used directly without copying; the size is taken from meta.generic.size.
 */
static int serializeMetaData(const char* protocol, const HsilStreamingMetaData& meta, SerializedMetaData& serMetaBuf)
{
    if (protocol == nullptr)
    {
        return -1;
    }

    /* Meta data for CAN protocol */
    if (*((const uint64_t*)(protocol)) == *((const uint64_t*)("CAN_v1\0")))
    {
        serMetaBuf.size = SerializedMetaData::HSIL_CAN_META_SIZE;
        memcpy(serMetaBuf.buffer, &meta.can.messageId, SerializedMetaData::HSIL_CAN_MESSAGE_ID_SIZE);
        serMetaBuf.buffer[SerializedMetaData::HSIL_CAN_MESSAGE_ID_SIZE] = static_cast<uint8_t>(meta.can.frameType);
        serMetaBuf.serialBuffer = serMetaBuf.buffer;
    }
    /* Meta data for Ethernet protocol */
    else if (*((const uint64_t*)(protocol)) == *((const uint64_t*)("Eth_v1\0")))
    {
        serMetaBuf.size = SerializedMetaData::HSIL_ETH_META_SIZE;
        serMetaBuf.buffer[0] = static_cast<uint8_t>(meta.eth.flags);
        serMetaBuf.serialBuffer = serMetaBuf.buffer;
    }
    /* Meta data for Jumbo Ethernet protocol */
    else if (*((const uint64_t*)(protocol)) == *((const uint64_t*)("EthJ_v1\0")))
    {
        serMetaBuf.size = SerializedMetaData::HSIL_ETHJ_META_SIZE;
        memcpy(serMetaBuf.buffer, &meta.ethj.mtu, SerializedMetaData::HSIL_ETHJ_MTU_SIZE);
        serMetaBuf.buffer[SerializedMetaData::HSIL_ETHJ_MTU_SIZE] = static_cast<uint8_t>(meta.ethj.flags);
        serMetaBuf.serialBuffer = serMetaBuf.buffer;
    }
    /* Meta data for generic protocol */
    else if (*((const uint64_t*)(protocol)) == *((const uint64_t*)("generic\0")))
    {
        if ((meta.generic.size > 0) && (meta.generic.data != nullptr))
        { 
            serMetaBuf.size = meta.generic.size;
            serMetaBuf.serialBuffer = meta.generic.data;
        }
        else
        {
            serMetaBuf.size = 0;
            serMetaBuf.serialBuffer = nullptr;
        }
    }
    else
    {
        std::cerr << "[HSIL] 'protocol' must be one of [\"generic\", \"CAN_v1\", \"Eth_v1\", \"EthJ_v1\"]; got '"
                  << protocol << "'.\n";
        return -1;
    }

    return 0;
}

/**
 * @brief Deserialize the meta data of a streaming sample from a byte buffer received over DDS.
 *       The deserialization format depends on the protocol and must match the serialization format described in serializeMetaData():
 *       - For "CAN_v1": 4 bytes for the frame type (little-endian uint32) followed by 1 byte for the flags.
 *       - For "Eth_v1": 1 byte for the flags.
 *       - For "EthJ_v1": 4 bytes for the MTU (little-endian uint32) followed by 1 byte for the flags.
 *       - For "generic": the user-supplied buffer is used directly without copying; the size is taken from serMetaBuf.size.
 */
static int deserializeMetaData(const char* protocol, const SerializedMetaData& serMetaBuf, HsilStreamingMetaData& meta)
{
    if (protocol == nullptr)
    {
        return -1;
    }

    /* Meta data for CAN protocol */
    if (*((const uint64_t*)(protocol)) == *((const uint64_t*)("CAN_v1\0")))
    {
        if ((serMetaBuf.size != SerializedMetaData::HSIL_CAN_META_SIZE) || (serMetaBuf.serialBuffer == nullptr))
        {
            std::cerr << "[HSIL] Invalid serialized meta data for CAN_v1 protocol. Expected size: " 
                      << SerializedMetaData::HSIL_CAN_META_SIZE << ", actual size: " << serMetaBuf.size << ".\n";
            return -1;
        }
        memcpy(&meta.can.messageId, serMetaBuf.serialBuffer, SerializedMetaData::HSIL_CAN_MESSAGE_ID_SIZE);
        meta.can.frameType = static_cast<HsilCanFrameType>(serMetaBuf.serialBuffer[SerializedMetaData::HSIL_CAN_MESSAGE_ID_SIZE]);
    }
    /* Meta data for Ethernet protocol */
    else if (*((const uint64_t*)(protocol)) == *((const uint64_t*)("Eth_v1\0")))
    {
        if ((serMetaBuf.size != SerializedMetaData::HSIL_ETH_META_SIZE) || (serMetaBuf.serialBuffer == nullptr))
        {
            std::cerr << "[HSIL] Invalid serialized meta data for Eth_v1 protocol. Expected size: " 
                      << SerializedMetaData::HSIL_ETH_META_SIZE << ", actual size: " << serMetaBuf.size << ".\n";
            return -1;
        }
        meta.eth.flags = serMetaBuf.serialBuffer[0];
    }
    /* Meta data for Jumbo Ethernet protocol */
    else if (*((const uint64_t*)(protocol)) == *((const uint64_t*)("EthJ_v1\0")))
    {
        if ((serMetaBuf.size != SerializedMetaData::HSIL_ETHJ_META_SIZE) || (serMetaBuf.serialBuffer == nullptr))
        {
            std::cerr << "[HSIL] Invalid serialized meta data for EthJ_v1 protocol. Expected size: " 
                      << SerializedMetaData::HSIL_ETHJ_META_SIZE << ", actual size: " << serMetaBuf.size << ".\n";
            return -1;
        }
        memcpy(&meta.ethj.mtu, serMetaBuf.serialBuffer, SerializedMetaData::HSIL_ETHJ_MTU_SIZE);
        meta.ethj.flags = serMetaBuf.serialBuffer[SerializedMetaData::HSIL_ETHJ_MTU_SIZE];
    }
    /* Meta data for generic protocol */
    else if (*((const uint64_t*)(protocol)) == *((const uint64_t*)("generic\0")))
    {
        meta.generic.size = serMetaBuf.size;
        meta.generic.data = const_cast<uint8_t*>(serMetaBuf.serialBuffer);
    }
    else
    {
        std::cerr << "[HSIL] 'protocol' must be one of [\"generic\", \"CAN_v1\", \"Eth_v1\", \"EthJ_v1\"]; got '"
                  << protocol << "'.\n";
        return -1;
    }

    return 0;
}

/*----------------------------------------------------------------------------*/
/* DATA-AVAILABLE LISTENERS                                                    */
/*----------------------------------------------------------------------------*/

/**
 * @brief Called by CycloneDDS when one or more GroupedData samples are available.
 *
 * Takes all pending samples via dds_take(), converts each valid one to the
 * HSIL GroupedData struct, and forwards it to the registered dispatch callback.
 */
static void onGroupedDataAvailable(dds_entity_t reader, void* vArg)
{
    auto* ctx = static_cast<CycloneGroupedReaderCtx*>(vArg);

    void*            samples[HSIL_MAX_SAMPLES] = {};
    dds_sample_info_t infos[HSIL_MAX_SAMPLES]  = {};

    const dds_return_t n = dds_take(reader, samples, infos, HSIL_MAX_SAMPLES, HSIL_MAX_SAMPLES);
    if (n < 0)
    {
        std::cerr << "[HSIL/CycloneDDS] dds_take failed: " << dds_strretcode(-n) << "\n";
        return;
    }

    for (dds_return_t i = 0; i < n; ++i)
    {
        if (!infos[i].valid_data)
        {
            continue;
        }

        auto* raw = static_cast<HSIL_CoSim_GroupedData*>(samples[i]);

        HsilGroupedData data;
        data.id             = raw->id;
        data.sequenceNumber = raw->sequenceNumber;
        data.timestamp      = raw->timestamp;
        data.data           = raw->data._buffer;
        data.dataSize       = static_cast<size_t>(raw->data._length);

        ctx->callback(ctx->topicName, &data, ctx->callbackData);
    }

    dds_return_loan(reader, samples, n);
}

/**
 * @brief Called by CycloneDDS when one or more StreamingData samples are available.
 */
static void onStreamingDataAvailable(dds_entity_t reader, void* vArg)
{
    auto* ctx = static_cast<CycloneStreamingReaderCtx*>(vArg);

    void*             samples[HSIL_MAX_SAMPLES] = {};
    dds_sample_info_t infos[HSIL_MAX_SAMPLES]   = {};

    const dds_return_t n = dds_take(reader, samples, infos, HSIL_MAX_SAMPLES, HSIL_MAX_SAMPLES);
    if (n < 0)
    {
        std::cerr << "[HSIL/CycloneDDS] dds_take failed: " << dds_strretcode(-n) << "\n";
        return;
    }

    for (dds_return_t i = 0; i < n; ++i)
    {
        if (!infos[i].valid_data)
        {
            continue;
        }

        auto* raw = static_cast<HSIL_CoSim_StreamingData*>(samples[i]);

        HsilStreamingData data;
        /* protocol is a fixed-size char[8]; copy it directly. */
        std::memcpy(data.protocol, raw->protocol, 8);
        data.timestamp = raw->timestamp;
        data.data      = raw->data._buffer;
        data.dataSize  = static_cast<size_t>(raw->data._length);

        /* Have to live with no meta data if deserialization fails. */
        if (deserializeMetaData(data.protocol, 
                                SerializedMetaData{raw->meta._length, raw->meta._buffer, {}}, 
                                data.meta) != 0)
        {
            std::cerr << "[HSIL/CycloneDDS] Failed to deserialize meta data from  StreamingData packet on topic '"
                      << ctx->topicName << "'. No meta data will be available\n";
        }

        ctx->callback(ctx->topicName, &data, ctx->callbackData);
    }

    dds_return_loan(reader, samples, n);
}

/*----------------------------------------------------------------------------*/
/* HELPER: QOS TRANSLATION                                                     */
/*----------------------------------------------------------------------------*/

/**
 * @brief Populate a CycloneDDS QoS object from an HsilQos struct.
 *
 * @param ddsQos Pre-allocated QoS object to populate.
 * @param qos    Pre-validated, non-NULL HsilQos.
 */
static void toCycloneQos(dds_qos_t* ddsQos, const HsilQos* qos)
{
    if (ddsQos == nullptr || qos == nullptr)
    {
        return;
    }

    /* History: keep the last N samples. */
    dds_qset_history(ddsQos, DDS_HISTORY_KEEP_LAST, static_cast<int32_t>(qos->queueLength));

    /* Reliability. */
    dds_reliability_kind_t reliabilityKind = DDS_RELIABILITY_BEST_EFFORT;
    switch(qos->reliability)
    {
        case HSIL_QOS_RELIABILITY_RELIABLE: {reliabilityKind = DDS_RELIABILITY_RELIABLE; break;}
        case HSIL_QOS_RELIABILITY_FAST:     {reliabilityKind = DDS_RELIABILITY_BEST_EFFORT; break;}
        /* Shouldn't happen since the QoS is pre-validated, but default to best-effort just in case. */
        default: {reliabilityKind = DDS_RELIABILITY_BEST_EFFORT; break;}
    }
    dds_qset_reliability(ddsQos, reliabilityKind, DDS_MSECS(100));

    /* Transport priority (advisory; may be ignored by the middleware).
     * NORMAL -> 0, LOW -> 1, HIGH -> 2. */
    int32_t transportPriority = 0;
    switch(qos->priority)
    {
        case HSIL_QOS_PRIORITY_HIGH:   {transportPriority = 2; break;}
        case HSIL_QOS_PRIORITY_LOW:    {transportPriority = 1; break;}
        case HSIL_QOS_PRIORITY_NORMAL: {transportPriority = 0; break;}
        /* Shouldn't happen since the QoS is pre-validated, but default to normal just in case. */
        default: {transportPriority = 0; break;}
    }
    dds_qset_transport_priority(ddsQos, transportPriority);
}

/*----------------------------------------------------------------------------*/
/* HELPER: TOPIC CREATION                                                      */
/*----------------------------------------------------------------------------*/

/**
 * @brief Create (or reuse) a DDS topic for GroupedData with the given name.
 *
 * CycloneDDS deduplicates topics by name and type within a participant, so
 * calling this for the same name multiple times is safe.
 *
 * @return Valid dds_entity_t on success, a negative DDS error code on failure.
 */
static dds_entity_t createGroupedTopic(dds_entity_t participant, const char* topicName)
{
    dds_entity_t topic = dds_create_topic(
        participant,
        &HSIL_CoSim_GroupedData_desc,
        topicName,
        nullptr,
        nullptr);

    if (topic < 0)
    {
        std::cerr << "[HSIL/CycloneDDS] Failed to create GroupedData topic '"
                  << topicName << "': " << dds_strretcode(-topic) << "\n";
    }

    return topic;
}

/**
 * @brief Create (or reuse) a DDS topic for StreamingData with the given name.
 */
static dds_entity_t createStreamingTopic(dds_entity_t participant, const char* topicName)
{
    dds_entity_t topic = dds_create_topic(
        participant,
        &HSIL_CoSim_StreamingData_desc,
        topicName,
        nullptr,
        nullptr);

    if (topic < 0)
    {
        std::cerr << "[HSIL/CycloneDDS] Failed to create StreamingData topic '"
                  << topicName << "': " << dds_strretcode(-topic) << "\n";
    }

    return topic;
}

/*----------------------------------------------------------------------------*/
/* VTABLE IMPLEMENTATIONS                                                      */
/*----------------------------------------------------------------------------*/

/** Initialize a CycloneDDS participant for the given domain. */
static void* cycloneInit(int domainId, const char* ddsConfigPath)
{
    /* 
     * The path is passed as-is (no "file://" prefix required).  CycloneDDS
     * first tries fopen() on the raw token; only if that fails does it attempt
     * to strip a "file://" prefix.  A plain absolute path therefore works on
     * both Linux (/etc/dds/config.xml) and Windows (C:\dds\config.xml).
     *
     * Limitation: a CycloneDDS domain is a process-wide singleton keyed by
     * domain ID.  CYCLONEDDS_URI is only read when the domain is first
     * created; subsequent participants on the same domain ID share that
     * existing configuration.  If the domain is already running a warning is
     * printed and the participant joins it regardless.  Use distinct domain
     * IDs to apply independent XML profiles. */
    if (ddsConfigPath != nullptr && ddsConfigPath[0] != '\0')
    {
        // const dds_return_t rc = ddsrt_setenv("CYCLONEDDS_URI", ddsConfigPath);
        // if (rc != DDS_RETCODE_OK)
        // {
        //     std::cerr << "[HSIL/CycloneDDS] Failed to set CYCLONEDDS_URI to '"
        //               << ddsConfigPath << "' (rc=" << rc << ")\n";
        // }
        dds_entity_t domain = dds_create_domain(
            static_cast<dds_domainid_t>(domainId), ddsConfigPath);

        if (domain < 0)
        {
            // Exit if any other error except the domain tried to be re-created with a different configuration.
            if (domain != DDS_RETCODE_PRECONDITION_NOT_MET)
            {
                std::cerr << "[HSIL/CycloneDDS] Failed to create domain " << domainId
                        << " with config '" << ddsConfigPath << "': "
                        << dds_strretcode(-domain) << "\n";
                return nullptr;
            }
            
            std::cout << "[HSIL/CycloneDDS] Domain " << domainId
                        << " already exists with a different configuration. Ignoring the new configuration.\n";
        }    
    }

    auto* ctx = new (std::nothrow) CycloneCtx{};
    if (ctx == nullptr)
    {
        return nullptr;
    }

    ctx->participant = dds_create_participant(
        static_cast<dds_domainid_t>(domainId), nullptr, nullptr);

    if (ctx->participant < 0)
    {
        std::cerr << "[HSIL/CycloneDDS] dds_create_participant failed (domain "
                  << domainId << "): " << dds_strretcode(-ctx->participant) << "\n";
        delete ctx;
        return nullptr;
    }

    return ctx;
}

/** Delete the DDS participant and free the vendor context. */
static void cycloneDestroy(void* vCtx)
{
    if (vCtx == nullptr)
    {
        return;
    }

    auto* ctx = static_cast<CycloneCtx*>(vCtx);
    dds_delete(ctx->participant); /* Cascades: deletes all child entities. */
    delete ctx;
}

/** Create a DDS DataWriter for GroupedData on the given topic. */
static void* cycloneCreateGroupedWriter(void* vCtx, const char* topicName, const HsilQos* qos)
{
    auto* ctx = static_cast<CycloneCtx*>(vCtx);

    const dds_entity_t topic = createGroupedTopic(ctx->participant, topicName);
    if (topic < 0)
    {
        return nullptr;
    }

    dds_qos_t* ddsQos = dds_create_qos();
    if (ddsQos == nullptr)
    {
        std::cerr << "[HSIL/CycloneDDS] Failed to create Qos object of GroupedData writer for '"
                  << topicName << "'\n";
        dds_delete(topic);
        return nullptr;
    }

    /* Apply the requested Qos settings. A valid qos object is expected or settings will be ignored. */
    toCycloneQos(ddsQos, qos);
    
    /* Create cyclone dds writer. */
    const dds_entity_t writer = dds_create_writer(ctx->participant, topic, ddsQos, nullptr);
    dds_delete_qos(ddsQos);
    dds_delete(topic); /* The writer implicitly holds a reference; we can release ours. */

    if (writer < 0)
    {
        std::cerr << "[HSIL/CycloneDDS] Failed to create GroupedData writer for '"
                  << topicName << "': " << dds_strretcode(-writer) << "\n";
        return nullptr;
    }

    /* Return the entity id as a pointer value; the abstraction layer treats it opaquely. */
    return reinterpret_cast<void*>(static_cast<intptr_t>(writer));
}

/** Create a DDS DataWriter for StreamingData on the given topic. */
static void* cycloneCreateStreamingWriter(void* vCtx, const char* topicName, const HsilQos* qos)
{
    auto* ctx = static_cast<CycloneCtx*>(vCtx);

    const dds_entity_t topic = createStreamingTopic(ctx->participant, topicName);
    if (topic < 0)
    {
        return nullptr;
    }

    dds_qos_t* ddsQos = dds_create_qos();
    if (ddsQos == nullptr)
    {
        std::cerr << "[HSIL/CycloneDDS] Failed to create Qos object of StreamingData writer for '"
                  << topicName << "'\n";
        dds_delete(topic);
        return nullptr;
    }

    /* Apply the requested Qos settings. A valid qos object is expected or settings will be ignored. */
    toCycloneQos(ddsQos, qos);

    /* Create cyclone dds writer. */
    const dds_entity_t writer = dds_create_writer(ctx->participant, topic, ddsQos, nullptr);
    dds_delete_qos(ddsQos);
    dds_delete(topic);

    if (writer < 0)
    {
        std::cerr << "[HSIL/CycloneDDS] Failed to create StreamingData writer for '"
                  << topicName << "': " << dds_strretcode(-writer) << "\n";
        return nullptr;
    }

    return reinterpret_cast<void*>(static_cast<intptr_t>(writer));
}

/** Delete a DDS DataWriter. */
static void cycloneDestroyWriter(void* /*vCtx*/, void* writer)
{
    if (writer == nullptr)
    {
        return;
    }

    const dds_entity_t entity = static_cast<dds_entity_t>(
        reinterpret_cast<intptr_t>(writer));
    dds_delete(entity);
}

/** Write a GroupedData sample to the DDS network. */
static int cycloneWriteGrouped(void* /*vCtx*/, void* writer, const HsilGroupedData* sample)
{
    HSIL_CoSim_GroupedData ddsSample;
    ddsSample.id             = sample->id;
    ddsSample.sequenceNumber = sample->sequenceNumber;
    ddsSample.timestamp      = sample->timestamp;

    /* Point directly at the caller's buffer – CycloneDDS copies before returning. */
    ddsSample.data._length  = static_cast<uint32_t>(sample->dataSize);
    ddsSample.data._maximum = static_cast<uint32_t>(sample->dataSize);
    ddsSample.data._buffer  = const_cast<uint8_t*>(sample->data);
    ddsSample.data._release = false;

    const dds_entity_t entity = static_cast<dds_entity_t>(
        reinterpret_cast<intptr_t>(writer));

    const dds_return_t rc = dds_write(entity, &ddsSample);
    if (rc != DDS_RETCODE_OK)
    {
        std::cerr << "[HSIL/CycloneDDS] dds_write (GroupedData) failed: "
                  << dds_strretcode(-rc) << "\n";
        return -1;
    }

    return 0;
}

/** Write a StreamingData sample to the DDS network. */
static int cycloneWriteStreaming(void* vCtx, void* writer, const HsilStreamingData* sample)
{
    SerializedMetaData serMetaBuf{0, nullptr, {}};

    /* Serialize meta data */
    if (serializeMetaData(sample->protocol, sample->meta, serMetaBuf) != 0)
    {
        std::cerr << "[HSIL/CycloneDDS] Failed to serialize meta data from StreamingData packet. No meta data will be sent\n";
        return -1;
    }

    HSIL_CoSim_StreamingData ddsSample;
    std::memcpy(ddsSample.protocol, sample->protocol, 8);
    ddsSample.timestamp = sample->timestamp;

    ddsSample.meta._length  = static_cast<uint32_t>(serMetaBuf.size);
    ddsSample.meta._maximum = static_cast<uint32_t>(serMetaBuf.size);
    ddsSample.meta._buffer  = const_cast<uint8_t*>(serMetaBuf.serialBuffer);
    ddsSample.meta._release = false;

    ddsSample.data._length  = static_cast<uint32_t>(sample->dataSize);
    ddsSample.data._maximum = static_cast<uint32_t>(sample->dataSize);
    ddsSample.data._buffer  = const_cast<uint8_t*>(sample->data);
    ddsSample.data._release = false;

    const dds_entity_t entity = static_cast<dds_entity_t>(
        reinterpret_cast<intptr_t>(writer));

    const dds_return_t rc = dds_write(entity, &ddsSample);
    if (rc != DDS_RETCODE_OK)
    {
        std::cerr << "[HSIL/CycloneDDS] dds_write (StreamingData) failed: "
                  << dds_strretcode(-rc) << "\n";
        return -1;
    }

    return 0;
}

/** Create a DDS DataReader for GroupedData with a data-available listener. */
static void* cycloneCreateGroupedReader(void*                   vCtx,
                                         const char*             topicName,
                                         const HsilQos*          qos,
                                         HsilGroupedDataCallback callback,
                                         void*                   callbackData)
{
    auto* ctx = static_cast<CycloneCtx*>(vCtx);

    const dds_entity_t topic = createGroupedTopic(ctx->participant, topicName);
    if (topic < 0)
    {
        return nullptr;
    }

    /* Allocate the listener context – freed in cycloneDestroyReader(). */
    auto* listenerCtx = new (std::nothrow) CycloneGroupedReaderCtx{};
    if (listenerCtx == nullptr)
    {
        dds_delete(topic);
        return nullptr;
    }

    listenerCtx->callback     = callback;
    listenerCtx->callbackData = callbackData;
    std::strncpy(listenerCtx->topicName, topicName, sizeof(listenerCtx->topicName) - 1);
    listenerCtx->topicName[sizeof(listenerCtx->topicName) - 1] = '\0';

    dds_listener_t* listener = dds_create_listener(listenerCtx);
    dds_lset_data_available(listener, onGroupedDataAvailable);

    dds_qos_t* ddsQos = dds_create_qos();
    if (ddsQos == nullptr)
    {
        std::cerr << "[HSIL/CycloneDDS] Failed to create Qos object of GroupedData reader for '"
                  << topicName << "'\n";
        dds_delete(topic);
        return nullptr;
    }

    /* Apply the requested Qos settings. A valid qos object is expected or settings will be ignored. */
    toCycloneQos(ddsQos, qos);

    /* Ignore local publication from the same participant. */
    dds_qset_ignorelocal(ddsQos, DDS_IGNORELOCAL_PARTICIPANT);

    /* Create cyclone dds reader.*/
    const dds_entity_t reader = dds_create_reader(
        ctx->participant, topic, ddsQos, listener);
    dds_delete_qos(ddsQos);
    dds_delete(topic);

    if (reader < 0)
    {
        std::cerr << "[HSIL/CycloneDDS] Failed to create GroupedData reader for '"
                  << topicName << "': " << dds_strretcode(-reader) << "\n";
        dds_delete_listener(listener);
        delete listenerCtx;
        return nullptr;
    }

    /* Wrap the reader and its associated resources in a heap handle. */
    auto* handle = new (std::nothrow) CycloneReaderHandle{};
    if (handle == nullptr)
    {
        dds_delete(reader);
        dds_delete_listener(listener);
        delete listenerCtx;
        return nullptr;
    }

    handle->reader      = reader;
    handle->listener    = listener;
    handle->listenerCtx = listenerCtx;
    handle->deleteCtx   = [](void* p) { delete static_cast<CycloneGroupedReaderCtx*>(p); };

    return handle;
}

/** Create a DDS DataReader for StreamingData with a data-available listener. */
static void* cycloneCreateStreamingReader(void*                     vCtx,
                                           const char*               topicName,
                                           const HsilQos*            qos,
                                           HsilStreamingDataCallback callback,
                                           void*                     callbackData)
{
    auto* ctx = static_cast<CycloneCtx*>(vCtx);

    const dds_entity_t topic = createStreamingTopic(ctx->participant, topicName);
    if (topic < 0)
    {
        return nullptr;
    }

    auto* listenerCtx = new (std::nothrow) CycloneStreamingReaderCtx{};
    if (listenerCtx == nullptr)
    {
        dds_delete(topic);
        return nullptr;
    }

    listenerCtx->callback     = callback;
    listenerCtx->callbackData = callbackData;
    std::strncpy(listenerCtx->topicName, topicName, sizeof(listenerCtx->topicName) - 1);
    listenerCtx->topicName[sizeof(listenerCtx->topicName) - 1] = '\0';

    dds_listener_t* listener = dds_create_listener(listenerCtx);
    dds_lset_data_available(listener, onStreamingDataAvailable);

    dds_qos_t* ddsQos = dds_create_qos();
    if (ddsQos == nullptr)
    {
        std::cerr << "[HSIL/CycloneDDS] Failed to create Qos object of StreamingData reader for '"
                  << topicName << "'\n";
        dds_delete(topic);
        return nullptr;
    }

    /* Apply the requested Qos settings. A valid qos object is expected or settings will be ignored. */
    toCycloneQos(ddsQos, qos);

    /* Ignore local publication from the same participant. */
    dds_qset_ignorelocal(ddsQos, DDS_IGNORELOCAL_PARTICIPANT);

    const dds_entity_t reader = dds_create_reader(
        ctx->participant, topic, ddsQos, listener);
    dds_delete_qos(ddsQos);
    dds_delete(topic);

    if (reader < 0)
    {
        std::cerr << "[HSIL/CycloneDDS] Failed to create StreamingData reader for '"
                  << topicName << "': " << dds_strretcode(-reader) << "\n";
        dds_delete_listener(listener);
        delete listenerCtx;
        return nullptr;
    }

    auto* handle = new (std::nothrow) CycloneReaderHandle{};
    if (handle == nullptr)
    {
        dds_delete(reader);
        dds_delete_listener(listener);
        delete listenerCtx;
        return nullptr;
    }

    handle->reader      = reader;
    handle->listener    = listener;
    handle->listenerCtx = listenerCtx;
    handle->deleteCtx   = [](void* p) { delete static_cast<CycloneStreamingReaderCtx*>(p); };

    return handle;
}

/** Destroy a reader and free all associated resources. */
static void cycloneDestroyReader(void* /*vCtx*/, void* vHandle)
{
    if (vHandle == nullptr)
    {
        return;
    }

    auto* handle = static_cast<CycloneReaderHandle*>(vHandle);
    dds_delete(handle->reader);
    dds_delete_listener(handle->listener);
    handle->deleteCtx(handle->listenerCtx);
    delete handle;
}

/**
 * @brief Translate a CycloneDDS QoS policy id into the HSIL diagnostic enum.
 *
 * Only the reliability policy corresponds to a setting that HSIL itself
 * exposes through HsilQos. Every other policy can only originate from a
 * third-party DDS endpoint and is reported as HSIL_QOS_MISMATCH_OTHER.
 */
static HsilQosMismatchPolicy toHsilMismatchPolicy(uint32_t totalCount, int32_t policyId)
{
    if (totalCount == 0)
    {
        return HSIL_QOS_MISMATCH_NONE;
    }
    
    if (policyId == DDS_RELIABILITY_QOS_POLICY_ID)
    {
        return HSIL_QOS_MISMATCH_RELIABILITY;
    }

    return HSIL_QOS_MISMATCH_OTHER;
}

/** Query the match and QoS compatibility status of a writer or reader. */
static int cycloneGetEndpointStatus(void* /*vCtx*/, void* endpoint, int isWriter, HsilEndpointStatus* status)
{
    status->matchedCount            = 0;
    status->qosMismatchCount        = 0;
    status->lastMismatchedQosPolicy = HSIL_QOS_MISMATCH_NONE;

    if (isWriter != 0)
    {
        /* Writers are returned to the abstraction layer as a bare entity id. */
        const dds_entity_t writer = static_cast<dds_entity_t>(reinterpret_cast<intptr_t>(endpoint));

        dds_publication_matched_status_t     matched{};
        dds_offered_incompatible_qos_status_t incompatible{};

        dds_return_t rc = dds_get_publication_matched_status(writer, &matched);
        if (rc != DDS_RETCODE_OK)
        {
            std::cerr << "[HSIL/CycloneDDS] Failed to read publication matched status: "
                      << dds_strretcode(-rc) << "\n";
            return -1;
        }

        rc = dds_get_offered_incompatible_qos_status(writer, &incompatible);
        if (rc != DDS_RETCODE_OK)
        {
            std::cerr << "[HSIL/CycloneDDS] Failed to read offered incompatible QoS status: "
                      << dds_strretcode(-rc) << "\n";
            return -1;
        }

        status->matchedCount            = static_cast<int>(matched.current_count);
        status->qosMismatchCount        = static_cast<int>(incompatible.total_count);
        status->lastMismatchedQosPolicy = toHsilMismatchPolicy(incompatible.total_count,
                                                               incompatible.last_policy_id);
    }
    else
    {
        auto* handle = static_cast<CycloneReaderHandle*>(endpoint);

        dds_subscription_matched_status_t        matched{};
        dds_requested_incompatible_qos_status_t  incompatible{};

        dds_return_t rc = dds_get_subscription_matched_status(handle->reader, &matched);
        if (rc != DDS_RETCODE_OK)
        {
            std::cerr << "[HSIL/CycloneDDS] Failed to read subscription matched status: "
                      << dds_strretcode(-rc) << "\n";
            return -1;
        }

        rc = dds_get_requested_incompatible_qos_status(handle->reader, &incompatible);
        if (rc != DDS_RETCODE_OK)
        {
            std::cerr << "[HSIL/CycloneDDS] Failed to read requested incompatible QoS status: "
                      << dds_strretcode(-rc) << "\n";
            return -1;
        }

        status->matchedCount            = static_cast<int>(matched.current_count);
        status->qosMismatchCount        = static_cast<int>(incompatible.total_count);
        status->lastMismatchedQosPolicy = toHsilMismatchPolicy(incompatible.total_count,
                                                               incompatible.last_policy_id);
    }

    return 0;
}

/*----------------------------------------------------------------------------*/
/* VTABLE INSTANCE                                                             */
/*----------------------------------------------------------------------------*/

/** Static vtable instance for the CycloneDDS backend. */
static const HsilDdsOps kCycloneDdsOps =
{
    cycloneInit,
    cycloneDestroy,
    cycloneCreateGroupedWriter,
    cycloneCreateStreamingWriter,
    cycloneDestroyWriter,
    cycloneWriteGrouped,
    cycloneWriteStreaming,
    cycloneCreateGroupedReader,
    cycloneCreateStreamingReader,
    cycloneDestroyReader,
    cycloneGetEndpointStatus
};

/*----------------------------------------------------------------------------*/
/* VENDOR REGISTRATION                                                         */
/*----------------------------------------------------------------------------*/

const HsilDdsOps* hsil_getDdsOps(void)
{
    return &kCycloneDdsOps;
}
